# Generated by Django 2.1.1 on 2018-10-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portofolio_site',
            new_name='portfolio_site',
        ),
    ]
